version: '2'
services:
    gatewayeventhub-app:
        image: gatewayeventhub
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gatewayeventhub-mysql:3306/gatewayeventhub?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8087:8087
    gatewayeventhub-mysql:
        extends:
            file: mysql.yml
            service: gatewayeventhub-mysql
